export function getData() {
    const tasks = {
        data: [
            {
                id: "1",
                text: "00-260(44)",
                start_date: "01-04-2025",
                end_date: "05-04-2025",
                deviation: '',
                priority: '',
                quantity: '',
                unitPrice: '',
                percent: '',
                dce: '',
                order: 10,
                progress: 0.4,
                open: true,
                taskType: 'order',
                nomenclature: '',
                product: "Редуктор_РК-231",
                laborIntensity: '',
                customer: '',
                productivity: '',
                cost: 5400,
                purchase: 5400,
                blank: 5400,
            },
            {
                id: "10",
                text: "020 Токарная",
                start_date: "02-04-2025",
                end_date: "03-04-2025",
                deviation: '2',
                priority: '1',
                quantity: '3',
                unitPrice: '',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 10,
                progress: 0.6,
                open: true,
                parent: "1",
                taskType: 'operation',
                Number: "020",
                Name: 'Токарная',
                gild: '',
                technicalprocess: '223.2332.42',
                outfit: '',
                codeOperation: "4110",
                laborIntensity: "2",
                cost: 5000,
            },
            {
                id: "100",
                text: "Pegas 380",
                start_date: "01-04-2025",
                end_date: "03-04-2025",
                deviation: '',
                priority: '',
                quantity: '',
                unitPrice: '',
                percent: '',
                dce: '',
                order: 20,
                progress: 0.6,
                parent: "10",
                taskType: 'resources',
                description: "Фрезерный универсальный станок 5 осей ЧПУ",
                typical: '',
                system: '',
                nowstatus: '',
                Name: '',
                Surname: '',
                SecSurname: '',
                Profession: '',
                rank: '',
                UIN: '',
                Current_status: '',
            },
            {
                id: "2",
                text: "00-260(44)",
                start_date: "01-04-2025",
                end_date: "05-04-2025",
                deviation: '',
                priority: '',
                quantity: '',
                unitPrice: '',
                percent: '',
                dce: '',
                order: 10,
                progress: 0.4,
                open: true,
                taskType: 'order',
                nomenclature: '',
                product: "Редуктор_РК-231",
                laborIntensity: '',
                customer: '',
                productivity: '',
                cost: 5400,
                purchase: 5400,
                blank: 5400,
            },
            {
                id: "20",
                text: "020 Токарная",
                start_date: "02-04-2025",
                end_date: "03-04-2025",
                deviation: '2',
                priority: '1',
                quantity: '3',
                unitPrice: '',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 10,
                progress: 0.6,
                open: true,
                parent: "2",
                taskType: 'operation',
                Number: "020",
                Name: 'Токарная',
                gild: '',
                technicalprocess: '223.2332.42',
                outfit: '',
                codeOperation: "4110",
                laborIntensity: "2",
                cost: 5000,
            },
            {
                id: "200",
                text: "Pegas 380",
                start_date: "01-04-2025",
                end_date: "03-04-2025",
                deviation: '',
                priority: '',
                quantity: '',
                unitPrice: '',
                percent: '',
                dce: '',
                order: 20,
                progress: 0.6,
                parent: "20",
                taskType: 'resources',
                description: "Фрезерный универсальный станок 5 осей ЧПУ",
                typical: '',
                system: '',
                nowstatus: '',
                Name: '',
                Surname: '',
                SecSurname: '',
                Profession: '',
                rank: '',
                UIN: '',
                Current_status: '',
            },
        ],
        links: [{ id: 1, source: 1, target: 2, type: "0" }],
    };

    return tasks;
}
