export function getData() {
    const tasks = {
        data: [
            {
                id: "1",
                text: "00-260(44)",
                start_date: "01-04-2025",
                end_date: "05-04-2025",
                plan_date: '01.04.2025',
                actual_date: '01.04.2025',
                deviation: '3',
                priority: '1',
                quantity: '2',
                unitPrice: '4000',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 10,
                progress: 0.4,
                open: true,
                taskType: 'order',
                nomenclature: 'РК-231.45.33.77_Шестерня',
                product: "Редуктор_РК-231",
                laborIntensity: '4',
                customer: 'ООО_Антей',
                productivity: '0',
                cost: '5400',
                purchase: '0',
                blank: 'Круг_стальной_ГОСТ_380-2005_СтЗсп',
            },
            {
                id: "10",
                text: "020 Токарная",
                start_date: "02-04-2025",
                end_date: "03-04-2025",
                plan_date: '01.04.2025',
                actual_date: '01.04.2025',
                deviation: '2',
                priority: '1',
                quantity: '3',
                unitPrice: '4000',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 10,
                progress: 0.6,
                open: true,
                parent: "1",
                taskType: 'operation',
                number: "020",
                name: 'Токарная',
                gild: '2',
                technicalProcess: '223.2332.42',
                outfit: 'Н3000423',
                codeOperation: "4110",
                laborIntensity: "2",
                cost: '2100',
            },
            {
                id: "100",
                text: "Pegas 380",
                start_date: "01-04-2025",
                end_date: "03-04-2025",
                plan_date: '01.04.2025',
                actual_date: '01.04.2025',
                deviation: '3',
                priority: '1',
                quantity: '2',
                unitPrice: '4000',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 20,
                progress: 0.6,
                parent: "10",
                taskType: 'resources',
                description: "Фрезерный универсальный станок 5 осей ЧПУ",
                gild: '12',
                typical: 'Оборудование ЧПУ',
                system: null,
                nowstatus: 'Техобслуживание',
                uin: '3T3555',
            },
            {
                id: "101",
                text: "Слесарь",
                start_date: "01-04-2025",
                end_date: "03-04-2025",
                plan_date: '01.04.2025',
                actual_date: '01.04.2025',
                deviation: '3',
                priority: '1',
                quantity: '2',
                unitPrice: '4000',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 20,
                progress: 0.6,
                parent: "10",
                taskType: 'worker',
                description: "Фрезерный универсальный станок 5 осей ЧПУ",
                gild: '12',
                name: 'Алексей',
                surname: 'Смотраков',
                secSurname: 'Владимирович',
                profession: 'Слесарь',
                rank: '4',
                uin: 'P567723',
                current_status: 'Техобслуживание',
            },
            {
                id: "2",
                text: "02-450(34)",
                start_date: "01-04-2025",
                end_date: "05-04-2025",
                plan_date: '01.04.2025',
                actual_date: '01.04.2025',
                deviation: '5',
                priority: '2',
                quantity: '2',
                unitPrice: '5000',
                percent: '50',
                dce: 'КТ15.263.27',
                order: 10,
                progress: 0.4,
                open: true,
                taskType: 'order',
                nomenclature: 'РК-231.45.33.77_Шестерня',
                product: "Редуктор_РК-231",
                laborIntensity: '4',
                customer: 'ООО_Антей',
                productivity: '0',
                cost: '5400',
                purchase: '0',
                blank: 'Круг_стальной_ГОСТ_380-2005_СтЗсп',
            },
            {
                id: "20",
                text: "020 Токарная",
                start_date: "02-04-2025",
                end_date: "03-04-2025",
                plan_date: '01.04.2025',
                actual_date: '01.04.2025',
                deviation: '2',
                priority: '1',
                quantity: '3',
                unitPrice: '4000',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 10,
                progress: 0.6,
                open: true,
                parent: "2",
                taskType: 'operation',
                number: "020",
                name: 'Токарная',
                gild: '2',
                technicalprocess: '223.2332.42',
                outfit: 'Н3000423',
                codeOperation: "4110",
                laborIntensity: "2",
                cost: '2100',
            },
            {
                id: "200",
                text: "Pegas 380",
                start_date: "01-04-2025",
                end_date: "03-04-2025",
                plan_date: '01.04.2025',
                actual_date: '01.04.2025',
                deviation: '3',
                priority: '1',
                quantity: '2',
                unitPrice: '4000',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 20,
                progress: 0.6,
                parent: "20",
                taskType: 'resources',
                description: "Фрезерный универсальный станок 5 осей ЧПУ",
                gild: '3',
                typical: 'Оборудование ЧПУ',
                system: null,
                nowstatus: 'Техобслуживание',
                uin: '3T3555',
            },
            {
                id: "201",
                text: "Слесарь",
                start_date: "01-04-2025",
                end_date: "03-04-2025",
                plan_date: '01.04.2025',
                actual_date: '01.04.2025',
                deviation: '3',
                priority: '1',
                quantity: '2',
                unitPrice: '4000',
                percent: '50',
                dce: 'РТ65.233.25',
                order: 20,
                progress: 0.6,
                parent: "20",
                taskType: 'worker',
                description: "Фрезерный универсальный станок 5 осей ЧПУ",
                gild: '12',
                name: 'Алексей',
                surname: 'Смотраков',
                secSurname: 'Владимирович',
                profession: 'Слесарь',
                rank: '4',
                uin: 'P567723',
                current_status: 'Техобслуживание',
            },
        ],
        links: [{ id: 1, source: 1, target: 2, type: "0" }],
    };

    return tasks;
}
